<?php

namespace ContainerDAJB26n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M3yRtGaService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.m3yRtGa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m3yRtGa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LibraryController::createLibrary' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LibraryController::deleteLibraryById' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LibraryController::reset' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LibraryController::updateLibraryGet' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Controller\\LibraryController::updateLibraryPost' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LibraryController::viewAllLibrary' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Controller\\LibraryController::viewLibraryById' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Controller\\LibraryControllerJson::findByIsbn' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Controller\\LibraryControllerJson::showAllBooks' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LibraryController:createLibrary' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LibraryController:deleteLibraryById' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LibraryController:reset' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LibraryController:updateLibraryGet' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Controller\\LibraryController:updateLibraryPost' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\LibraryController:viewAllLibrary' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Controller\\LibraryController:viewLibraryById' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Controller\\LibraryControllerJson:findByIsbn' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'App\\Controller\\LibraryControllerJson:showAllBooks' => ['privates', '.service_locator.mFXXG35', 'get_ServiceLocator_MFXXG35Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LibraryController::createLibrary' => '?',
            'App\\Controller\\LibraryController::deleteLibraryById' => '?',
            'App\\Controller\\LibraryController::reset' => '?',
            'App\\Controller\\LibraryController::updateLibraryGet' => '?',
            'App\\Controller\\LibraryController::updateLibraryPost' => '?',
            'App\\Controller\\LibraryController::viewAllLibrary' => '?',
            'App\\Controller\\LibraryController::viewLibraryById' => '?',
            'App\\Controller\\LibraryControllerJson::findByIsbn' => '?',
            'App\\Controller\\LibraryControllerJson::showAllBooks' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LibraryController:createLibrary' => '?',
            'App\\Controller\\LibraryController:deleteLibraryById' => '?',
            'App\\Controller\\LibraryController:reset' => '?',
            'App\\Controller\\LibraryController:updateLibraryGet' => '?',
            'App\\Controller\\LibraryController:updateLibraryPost' => '?',
            'App\\Controller\\LibraryController:viewAllLibrary' => '?',
            'App\\Controller\\LibraryController:viewLibraryById' => '?',
            'App\\Controller\\LibraryControllerJson:findByIsbn' => '?',
            'App\\Controller\\LibraryControllerJson:showAllBooks' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
