<?php

namespace ContainerLDP7NYS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_XWuUo6cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.xWuUo6c' shared service.
     *
     * @return \App\Controller\SessionInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Card21Controller::playerHand21Get()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\SessionInterface". Did you forget to add a use statement?');
    }
}
