<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDAJB26n\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDAJB26n/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDAJB26n.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDAJB26n\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDAJB26n\App_KernelTestDebugContainer([
    'container.build_hash' => 'DAJB26n',
    'container.build_id' => '007f7ca5',
    'container.build_time' => 1717816686,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDAJB26n');
