<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPV0MTez\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPV0MTez/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPV0MTez.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPV0MTez\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPV0MTez\App_KernelDevDebugContainer([
    'container.build_hash' => 'PV0MTez',
    'container.build_id' => 'cf3a5fc9',
    'container.build_time' => 1718133983,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPV0MTez');
